/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class to_mumble_util_PrecisionTimer */

#ifndef _Included_to_mumble_util_PrecisionTimer
#define _Included_to_mumble_util_PrecisionTimer
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: m_has_impl */
/*
 * Class:     to_mumble_util_PrecisionTimer
 * Method:    getOsTimer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_to_mumble_util_PrecisionTimer_getOsTimer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
