dist: xenial
sudo: false

addons:
  chrome: stable

branches:
  except:
  - domui-1.0

jdk:
- openjdk11

language: java

install: true
script: mvn -q clean install -Dmaven.test.skip=false -Dmaven.javadoc.skip=true

cache:
  directories:
  - $HOME/.m2

deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/demo-deploy $DEPLOY_KEY
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: scripts/demo-deploy $DEPLOY_KEY
    on:
      branch: testing
  - provider: script
    skip_cleanup: true
    script: scripts/demo-deploy $DEPLOY_KEY
    on:
      branch: demo

before_script:
  - "export DISPLAY=:99.0"

before_install:
- scripts/beforeInstall
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

after_script:
  - echo "Creating maven report"
  - mvn site site:deploy -Dmaven.javadoc.skip=true
  - scripts/deploy-test-reports.sh

after_failure:
  - echo $( pwd )

