package to.etc.test.webapp.query.qfield;

import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.*;

import to.etc.domui.component.meta.*;

/**
 * Table fin_banks: Generated by GenHib
 * Created on Fri Dec 21 08:59:37 CET 2012
 */
@Entity
@GenericGenerator(name = "sq", strategy = "nl.itris.viewpoint.db.hibernate.ViewpointIdentifierGenerator", parameters = {@org.hibernate.annotations.Parameter(name = "sequence", value = "fin_fbk_seq")})
@Table(name = "fin_banks")
@MetaObject(defaultColumns = { //
	@MetaDisplayProperty(name = TestBank.pIDENTIFICATION, displayLength = 5, defaultSortable = SortableType.SORTABLE_ASC) //
	, @MetaDisplayProperty(name = TestBank.pBANKNAME, displayLength = 40, defaultSortable = SortableType.SORTABLE_ASC) //
	, @MetaDisplayProperty(name = TestBank.pBIC, displayLength = 10, defaultSortable = SortableType.SORTABLE_ASC) //
	, @MetaDisplayProperty(name = TestBank.pBLOCKED, displayLength = 5, defaultSortable = SortableType.SORTABLE_ASC)
//
	}, //
	searchProperties = { //
	@MetaSearchItem(name = TestBank.pBANKNAME, order = 1, searchType = SearchPropertyType.BOTH) //
	, @MetaSearchItem(name = TestBank.pCITYNAME, order = 2, searchType = SearchPropertyType.BOTH) //
	, @MetaSearchItem(name = TestBank.pFILENAME, order = 3, searchType = SearchPropertyType.BOTH) //
	, @MetaSearchItem(name = TestBank.pFILENAMESEPA, order = 4, searchType = SearchPropertyType.BOTH) //
	, @MetaSearchItem(name = TestBank.pBIC, order = 6, searchType = SearchPropertyType.BOTH) //
	, @MetaSearchItem(name = TestBank.pBLOCKED, order = 7, searchType = SearchPropertyType.BOTH) //
	, @MetaSearchItem(name = TestBank.pIDENTIFICATION, order = 8, searchType = SearchPropertyType.BOTH)
//
}) //
public class TestBank {
	private Long m_id;

	/** Column FBK_BANKNAME VARCHAR2(40) NOT NULL: Bank name */
	private String m_bankname;

	public static final String pBANKNAME = "bankname";

	/** Column FBK_BIC VARCHAR2(11) NOT NULL: Bank Identifier Code */
	private String m_bic;

	public static final String pBIC = "bic";

	/** Column FBK_BLOCKED_YN VARCHAR2(1) NOT NULL: Is the bank blocked or not */
	private boolean m_blocked;

	public static final String pBLOCKED = "blocked";

	/** Column FBK_CITYNAME VARCHAR2(40) NOT NULL: City of main central */
	private String m_cityname;

	public static final String pCITYNAME = "cityname";

	/** Column FBK_FILENAME VARCHAR2(8) NULL:  */
	private String m_filename;

	public static final String pFILENAME = "filename";

	/** Column FBK_FILENAME_SEPA VARCHAR2(8) NULL:  */
	private String m_filenameSepa;

	public static final String pFILENAMESEPA = "filenameSepa";

	/** Column FBK_IDENTIFICATION VARCHAR2(5) NOT NULL: Upper case short name, used as Primary Key in Decade */
	private String m_identification;

	public static final String pIDENTIFICATION = "identification";

	/**
	 * Column FBK_ID NUMBER(16, 0) NOT NULL
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sq")
	@Column(name = "FBK_ID", precision = 16, scale = 0, nullable = false)
	public Long getId() {
		return m_id;
	}

	public void setId(Long v) {
		m_id = v;
	}

	/**
	 * Column FBK_BANKNAME VARCHAR2(40) NOT NULL: Bank name
	 */
	@Column(name = "FBK_BANKNAME", length = 40, nullable = false)
	public String getBankname() {
		return m_bankname;
	}

	public void setBankname(String v) {
		m_bankname = v;
	}

	/**
	 * Column FBK_BIC VARCHAR2(11) NOT NULL: Bank Identifier Code
	 */
	@Column(name = "FBK_BIC", length = 11, nullable = false)
	public String getBic() {
		return m_bic;
	}

	public void setBic(String v) {
		m_bic = v;
	}

	/**
	 * Column FBK_BLOCKED_YN VARCHAR2(1) NOT NULL: Is the bank blocked or not
	 */
	@Column(name = "FBK_BLOCKED_YN", length = 1, nullable = false)
	@Type(type = "yes_no")
	public boolean isBlocked() {
		return m_blocked;
	}

	public void setBlocked(boolean v) {
		m_blocked = v;
	}

	/**
	 * Column FBK_CITYNAME VARCHAR2(40) NOT NULL: City of main central
	 */
	@Column(name = "FBK_CITYNAME", length = 40, nullable = false)
	public String getCityname() {
		return m_cityname;
	}

	public void setCityname(String v) {
		m_cityname = v;
	}

	/**
	 * Column FBK_FILENAME VARCHAR2(8) NULL:
	 */
	@Column(name = "FBK_FILENAME", length = 8, nullable = true)
	public String getFilename() {
		return m_filename;
	}

	public void setFilename(String v) {
		m_filename = v;
	}

	/**
	 * Column FBK_FILENAME_SEPA VARCHAR2(8) NULL:
	 */
	@Column(name = "FBK_FILENAME_SEPA", length = 8, nullable = true)
	public String getFilenameSepa() {
		return m_filenameSepa;
	}

	public void setFilenameSepa(String v) {
		m_filenameSepa = v;
	}

	/**
	 * Column FBK_IDENTIFICATION VARCHAR2(5) NOT NULL: Upper case short name, used as Primary Key in Decade
	 */
	@Column(name = "FBK_IDENTIFICATION", length = 5, nullable = false)
	public String getIdentification() {
		return m_identification;
	}

	public void setIdentification(String v) {
		m_identification = v;
	}
}
