package to.etc.server.ajax.eventmanager;

/**
 * Holds an event as generated by the code, and the data
 * needed to cleanup the event.
 *
 * @author <a href="mailto:jal@etc.to">Frits Jalvingh</a>
 * Created on Oct 25, 2006
 */
final public class QueuedEvent {
	/** The channel that this event fires on */
	private String	m_channel;

	private Object	m_data;

	/** The framework-assigned event ID */
	private int		m_eventID;

	/** The time the event was fired (for expiry pps) */
	private long	m_eventTS;

	public QueuedEvent(int eventID, long eventTS, String channel, Object data) {
		m_eventID = eventID;
		m_eventTS = eventTS;
		m_channel = channel;
		m_data = data;
	}

	QueuedEvent createCopy(Object newdata) {
		return new QueuedEvent(m_eventID, m_eventTS, m_channel, newdata);
	}

	public String getChannel() {
		return m_channel;
	}

	public Object getData() {
		return m_data;
	}

	public int getEventID() {
		return m_eventID;
	}

	long getEventTS() {
		return m_eventTS;
	}
}
