package to.etc.domuidemo.pages.basic;

import to.etc.domui.component.layout.*;
import to.etc.domui.component.layout.title.*;
import to.etc.domui.component.misc.*;
import to.etc.domui.dom.html.*;

public class CaptionsDemoPage extends UrlPage {
	@Override
	public void createContent() throws Exception {
		add(new InfoPanel( //
			"This is an <b>InfoPanel</b>. It shows a message inside a div, with an info icon at the side." //
				+ " It is allowed to contain simple HTML markup." //
				+ " All components on this page are inactive, meaning they are only used to layout, and do not have buttons to click on to change them." //
		));

		add(new VerticalSpacer(20));
		add(new CaptionedHeader("Captioned header"));
		Div x = new Div();
		add(x);
		x.setText("The captioned header (directly above this text) only shows a header and is used to separate parts on a page.");

		add(new VerticalSpacer(20));
		CaptionedPanel	cp	= new CaptionedPanel("Captioned panel");
		add(cp);
		cp.getContent().add("The captioned panel has a beveled title, and a separate content area within the panel which can contain whatever you want. Since it has a very \"busy\" look it should be used sparingly, and only for parts that really require the attention of the user.");

		add(new VerticalSpacer(20));
		add(new AppPageTitleBar("Page Title Bar", false));
		x = new Div();
		add(x);
		x.setText("The AppPageTitle class shows a title bar which can contain buttons, and which shows a beziered style element generated by a SVG image");

	}
}
