package to.etc.server.misc;

import to.etc.server.servlet.*;

/**
 * Represents a servlet generator: a thingy which is able to
 * generate the result for a servlet. A generator is used in
 * servlets that have several ways to output their data. 
 * 
 * Created on Feb 4, 2005
 * @author jal
 */
public interface AbstractGenerator {
	/**
	 * This returns the modification date for the document that would be
	 * generated by the input. It should return a real valid date if possible
	 * because the browser will use this date to determine whether the document
	 * needs to be cached. If you really don't know then return -1 which will
	 * disable browser caching.
	 * @return	-1 for this default implementation.
	 */
	public long getLastModified() throws Exception;

	/**
	 * This should generate the actual contents.
	 * @throws Exception
	 */
	public void generate(ContextServletContext ctx) throws Exception;
}
