firstName.label=First name
lastName.label=Last name
company.label=Company
address.label=Address
city.label=City
state.label=State
country.label=Country
postalCode.label=Postal code
phone.label=Phone
fax.label=Fax
email.label=Email
supportRepresentative.label=Support representative
