firstName.label=First name
lastName.label=Last name
title.label=Function
reportsTo.label=Reports to
reportsFrom.label=Direct reports
birthDate.label=Date of birth
dateHired.label=Hired on
address.label=Address
city.label=City
state.label=State
country.label=Country
postalCode.label=Postal code
phone.label=Phone
fax.label=Fax
email.label=Email
