#!/bin/bash
mkdir -p ~/bin
if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then
  openssl aes-256-cbc -K $encrypted_6430b1f3fcb1_key -iv $encrypted_6430b1f3fcb1_iv -in scripts/deployment_id_ecdsa.enc -out ~/deployment_id_ecdsa -d
fi
#wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O ~/phantomjs.tar.bz2
#tar xjf ~/phantomjs.tar.bz2 -C ~
#cp ~/phantomjs-2.1.1-linux-x86_64/bin/phantomjs ~/bin
wget -N http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -P ~/
unzip ~/chromedriver_linux64.zip -d ~/
rm ~/chromedriver_linux64.zip
mv ~/chromedriver ~/bin
chmod a+x ~/bin/chromedriver
export PATH=~/bin:$PATH
#echo "Phantomjs version"
#phantomjs -v
echo "ChromeDriver version"
chromedriver -v

# Install some fonts
echo "Installing fonts"
mkdir -p ~/.fonts
cp buildResources/fonts/* ~/.fonts
fc-cache -v
echo "Fonts in .fonts:"
ls -l ~/.fonts


