package to.etc.domuidemo.pages;

public class Lorem {
	static private final String[] LOREM = {
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at dapibus sem. Suspendisse sed ipsum sit amet velit dictum faucibus sit amet non risus. Suspendisse dignissim congue nisl, a malesuada urna feugiat ut. Proin luctus bibendum elementum. Phasellus convallis, magna in tincidunt laoreet, nisi dolor sagittis mi, sed euismod odio leo ac arcu. Nulla rhoncus risus et nisl sagittis ac lacinia dui ultricies. Donec quis accumsan lorem. Nulla ac libero ante, vel dignissim augue. Sed vehicula vestibulum dictum. Maecenas a vestibulum massa. Praesent dignissim ipsum vel tellus dapibus in commodo lorem gravida. Proin viverra, justo quis ultricies ultricies, turpis felis aliquet nibh, nec commodo purus lacus eu tortor.",
		"Cras lobortis ornare felis, ac posuere sem tempus sed. Integer nec porta urna. Duis congue auctor venenatis. Proin vulputate neque nec turpis placerat vitae lobortis turpis porta. Vestibulum vulputate risus id urna adipiscing nec tincidunt libero pharetra. Donec at purus libero. Nulla enim turpis, molestie vel accumsan in, volutpat iaculis neque. Curabitur ac gravida nibh. Donec vitae suscipit enim. Aenean tincidunt nibh ut erat cursus mollis. Vivamus eget purus eu magna varius varius. Morbi eu velit eros. Ut sagittis, est nec porta laoreet, tortor mauris lobortis purus, id dapibus nulla dolor quis dui.",
		"Duis posuere ante vel justo ultrices placerat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam lorem nibh, hendrerit in tempor vitae, semper sed tortor. Donec lobortis varius massa nec mattis. Proin condimentum semper augue at interdum. Vestibulum eget felis nec lacus semper hendrerit. Integer aliquam varius velit vel cursus. Aenean cursus gravida adipiscing. Fusce pharetra nunc a erat imperdiet ut egestas dolor rhoncus. Proin sed dolor in sem dictum commodo vel pellentesque lacus.",
		"Phasellus vehicula posuere dictum. Donec libero risus, blandit quis convallis sed, hendrerit vitae nulla. Quisque leo ante, placerat eu rhoncus et, vestibulum quis eros. Nam pretium placerat erat eget bibendum. Vestibulum nulla ipsum, dictum at pellentesque et, sodales sed lorem. Phasellus tempus diam dui. Nullam eget lorem vel leo mollis facilisis. Pellentesque et velit sit amet arcu vestibulum consectetur. Maecenas tristique sem in mauris ultricies ultricies. Aenean hendrerit imperdiet felis. Duis urna arcu, dignissim non rhoncus nec, porta at massa. Duis iaculis erat vel nisl blandit nec condimentum nibh suscipit. Pellentesque consequat interdum accumsan.",
		"Maecenas magna nunc, euismod et tristique id, interdum et ipsum. Ut tincidunt sapien vel enim vulputate et fermentum nisi elementum. Curabitur sit amet enim odio, sed scelerisque nibh. Pellentesque ornare ante et augue fringilla quis faucibus sem facilisis. Vivamus eget nunc id diam commodo varius ut id turpis. Nullam cursus, nunc in accumsan dictum, massa ligula fringilla diam, sed facilisis metus mauris sit amet metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ac dui ut urna aliquet dictum quis ac sapien. In elementum, mauris et dignissim rhoncus, massa mauris hendrerit lectus, id faucibus mauris odio in metus. Curabitur hendrerit consequat urna, vitae viverra quam mollis vel. Praesent vitae leo lacus. Suspendisse vehicula, nulla vel pharetra sagittis, ligula nisl scelerisque justo, vel ornare turpis nulla vitae erat.",
		"Phasellus a metus eu diam mattis tincidunt nec non quam. Cras sit amet ultricies purus. Suspendisse sodales diam sed dui blandit non molestie nibh ullamcorper. Sed ullamcorper velit a urna venenatis et sollicitudin purus tempor. Cras ac dolor ac mi suscipit ornare. Suspendisse sed augue varius enim ullamcorper posuere aliquam a massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer leo turpis, consequat blandit ultrices ut, rutrum vel ipsum. Donec non velit tortor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam vitae odio non massa rhoncus molestie. Aliquam luctus, mi sit amet sagittis fermentum, augue sem imperdiet quam, in volutpat sem velit non mi. Aliquam erat volutpat. Nullam accumsan velit sit amet velit fermentum vulputate. Cras in felis eget ante bibendum venenatis. Integer dignissim, est vitae consequat malesuada, est orci tristique nulla, non ullamcorper enim ligula facilisis mi. Nunc nulla elit, eleifend vitae ultricies at, dictum eu lacus. Donec massa mi, vulputate eget fringilla ac, tristique pulvinar mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit."
,
		"Sed eu ipsum quis sapien euismod dapibus sed sed sem. Donec vehicula pulvinar risus, sed auctor ligula lacinia et. Vestibulum pellentesque nulla ut nibh porttitor semper. Pellentesque eget orci ante. Vestibulum posuere rutrum leo, id imperdiet dolor adipiscing vitae. Nullam adipiscing sem quis libero accumsan in volutpat diam imperdiet. Nullam eget ante vitae nibh lobortis porttitor id non turpis. Integer bibendum nisl fringilla lectus aliquet tincidunt. Ut ut eros elit. Fusce ac massa mauris, dignissim sagittis risus. Fusce sit amet justo urna. Nunc in est aliquam est porta malesuada. Quisque ut nisi vel enim tristique rutrum. Nulla et sem tortor, ut ullamcorper velit. Quisque imperdiet bibendum tempor. Nam rutrum aliquam nisl ac ornare. Nunc sapien dui, lacinia non commodo at, scelerisque in neque. Vestibulum in leo quam.",
		"Proin non lacinia nulla. Nullam eu semper mauris. Ut dignissim, turpis at molestie tincidunt, leo leo egestas libero, at pellentesque massa libero consectetur justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla venenatis luctus libero sed vulputate. Pellentesque massa metus, luctus venenatis semper at, tincidunt a nisl. Integer viverra est vitae ipsum accumsan cursus. Pellentesque non massa sed nisl tincidunt dignissim tempus vel nibh. Curabitur a orci dui, vitae bibendum mi. Ut pulvinar, ante a consectetur aliquam, nunc justo cursus massa, eu blandit lacus nisi eget neque. Nunc dapibus leo vitae risus congue id viverra mi lacinia. Integer facilisis diam eget ipsum eleifend et lacinia lorem imperdiet. Morbi sit amet vestibulum magna. In non lectus erat. Morbi pretium, risus placerat fringilla posuere, purus risus auctor risus, nec aliquet leo ipsum nec eros. Etiam porta gravida blandit. Pellentesque lacinia enim velit, vitae facilisis diam.",
		"Cras ligula tortor, consectetur ut suscipit sed, posuere vel est. Quisque nunc dui, ultrices a cursus et, bibendum non tellus. Donec velit diam, condimentum ac dapibus ut, pharetra vitae enim. Morbi gravida leo et augue porta ut pharetra tellus ornare. In eleifend vehicula risus, eu auctor purus tincidunt sed. Proin sapien sapien, posuere quis vulputate et, malesuada non sapien. Etiam nec feugiat turpis. Aliquam turpis eros, placerat quis lobortis ac, fringilla aliquam leo. Cras suscipit felis vel ligula viverra eleifend. Sed gravida velit non nulla pretium at ultrices nibh interdum. Aenean non turpis tortor, sed suscipit mi. Curabitur quis lacus at nunc fringilla laoreet non sit amet risus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla facilisi. Nullam eget fermentum dolor. Quisque accumsan sem lobortis augue viverra id facilisis elit aliquet. Curabitur dictum bibendum orci, scelerisque suscipit elit ullamcorper eget. Quisque ac lacus nulla, at convallis lectus. Aliquam molestie pellentesque odio accumsan tincidunt."
,
		"Curabitur pretium pretium neque at lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec nec elit at sapien iaculis eleifend. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed sodales, orci id fermentum mattis, orci est aliquet ante, a vestibulum nisl dui at augue. Integer gravida, tellus in condimentum porttitor, eros erat condimentum magna, nec pretium velit ante sit amet turpis. Etiam eget iaculis lectus. Etiam gravida nunc sit amet nisi suscipit auctor. Duis molestie dignissim quam ut bibendum. Suspendisse fringilla nibh vel augue laoreet facilisis. Fusce id mi elit, ac ultrices lacus. Vivamus quis venenatis purus. Donec eget ipsum sem.",
		"Aliquam dictum, orci non commodo volutpat, sapien sem lobortis turpis, eu lobortis metus dolor a ligula. Ut tristique elementum justo et dictum. Mauris risus justo, sagittis non scelerisque a, laoreet ac leo. Nullam laoreet ullamcorper sapien, id dignissim ante mattis tincidunt. Nam sagittis aliquet sapien id consequat. In in mi ac sapien viverra varius. Morbi neque quam, auctor lobortis lobortis ac, mattis vitae odio. Cras urna metus, lacinia eu lobortis quis, vestibulum non dui. Nulla convallis, diam eget laoreet pretium, sem ante aliquam eros, eget vulputate enim nunc nec lacus. Maecenas dictum sollicitudin tellus eget tempus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		"Nullam eu quam purus, non egestas erat. Cras nisi elit, pharetra a tempus vel, consectetur ut libero. Mauris rhoncus odio ut est ornare et pretium felis eleifend. Vestibulum sollicitudin iaculis odio, vitae molestie nibh hendrerit at. Phasellus elit risus, varius sit amet ornare eget, faucibus sed mauris. Donec luctus eros ac lacus faucibus sed posuere diam fringilla. Phasellus laoreet aliquet rhoncus. Ut iaculis elit eu orci posuere feugiat. Suspendisse potenti. Donec ornare risus eu dolor ornare posuere quis eget nibh. Aenean interdum tincidunt odio at elementum.",
		"Nam ac tortor vestibulum tellus vehicula porttitor eget ac felis. Cras nulla mi, tincidunt et semper at, faucibus in sapien. Nulla eget ligula ipsum. Ut ultricies quam ut turpis accumsan convallis. Mauris ullamcorper ante id elit iaculis et pretium augue aliquet. Proin ut sapien magna, vitae fringilla nisi. Integer gravida nisi turpis, eu pulvinar tellus. Vivamus neque metus, aliquam quis ornare vitae, venenatis a metus. Fusce lacinia, magna in tincidunt ultricies, tellus nulla euismod nisl, ut elementum nisi mauris in dolor. In massa arcu, fermentum in commodo at, sollicitudin a tellus. Praesent leo lectus, bibendum dignissim facilisis ut, varius id augue. Etiam sit amet magna quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac viverra enim. Ut placerat pretium elit, non fringilla metus feugiat in.",
		"Integer ut metus est, sit amet dapibus nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla consectetur lectus eget mi varius id varius arcu ultrices. Cras felis massa, aliquam vel ultrices vel, accumsan a massa. Phasellus volutpat odio eu arcu mollis tincidunt. Cras hendrerit, dolor in lobortis egestas, nisl tortor viverra ipsum, et varius augue nulla sit amet lectus. Pellentesque sollicitudin euismod nunc id ullamcorper. Morbi elementum condimentum justo, a mollis lorem vestibulum a. Praesent at leo neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc turpis ante, bibendum a pulvinar id, porttitor ut nisl."
	};

	static private int m_paraid;

	static synchronized public String getPara() {
		int ix = m_paraid++;
		if(m_paraid >= LOREM.length)
			m_paraid = 0;
		return LOREM[ix];
	}

	static public String getSentences(int maxlength) {
		StringBuilder sb = new StringBuilder();
		String para = "";
		while(sb.length() < maxlength) {
			//-- We need to split another sentence off the current para
			if(para.length() == 0) {
				para = getPara();
			}
			int pos = para.indexOf('.');
			String seg = para.substring(0, pos + 1).trim();
			para = para.substring(pos + 1).trim();
			if(sb.length() > 0)
				sb.append(' ');
			sb.append(seg);
		}
		return sb.toString();
	}
}
