name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
#      - name: Initialize CodeQL
#        uses: github/codeql-action/init@v3
#      - name: Cache SonarQube packages
#        uses: actions/cache@v4
#        with:
#          path: ~/.sonar/cache
#          key: ${{ runner.os }}-sonar
#          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Build with Maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: mvn -P sonar -q --batch-mode --update-snapshots clean install sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.host.url=https://sonarcloud.io -Dmaven.javadoc.skip=true -DCI=true -Dskarp.targetdb.name=testdb${{ github.run_number }} -Dskarp.junitdb.name=fw_junit${{ github.run_number }}
        run: mvn -P sonar-domui --batch-mode --update-snapshots clean install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -DCI=true -Dskarp.targetdb.name=testdb${{ github.run_number }} -Dskarp.junitdb.name=fw_junit${{ github.run_number }}
      - name: Upload JUnit test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: to.etc.domui.demo/target/failsafe-reports/*.png
          retention-days: 7
#      - name: Perform CodeQL Analysis
#        uses: github/codeql-action/analyze@v3
